//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aviacompany.Antuh.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int ID_Flight { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public int ID_Team { get; set; }
        public int ID_Aircraft { get; set; }
        public int ID_Meteorology { get; set; }
        public Nullable<int> ID_DeparturePoint { get; set; }
        public Nullable<int> ID_ArrivalPoint { get; set; }
        public string Distance { get; set; }
        public bool Permission { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual ArrivalPoint ArrivalPoint { get; set; }
        public virtual DeparturePoint DeparturePoint { get; set; }
        public virtual Meteorology Meteorology { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
