//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aviacompany.Antuh.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<ArrivalPoint> ArrivalPoint { get; set; }
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Baggage> Baggage { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<DeparturePoint> DeparturePoint { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Hangar> Hangar { get; set; }
        public virtual DbSet<Income> Income { get; set; }
        public virtual DbSet<Meteorology> Meteorology { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Season> Season { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TypeBaggage> TypeBaggage { get; set; }
        public virtual DbSet<TypePlace> TypePlace { get; set; }
        public virtual DbSet<Visa> Visa { get; set; }
    }
}
